name: "[Issue Management] Pull Request Review Reminder"

on:
  workflow_dispatch:

  schedule:
    # Trigger every Monday at 10:00 GMT+8
    - cron: '0 2 * * 1'

jobs:
  pull-request-review-reminder:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACTION_TOKEN }}

    name: "Pull Request Review Reminder"

    steps:
    - name: Setup Git
      run: |
        gh auth setup-git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - uses: actions/checkout@v4

    - name: Pull Request Review Reminder
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_LONGHORN_QA_WEBHOOK_URL }}
        USER_MAPPING: ${{ secrets.USER_MAPPING_FOR_GITHUB_SLACK }}
      run: python .github/workflows/pr-review-reminder.py